Added vpnclient.config with AllowRemoteConfig set to true to fix problems with --network=host mode. Added another check for already existing adapter, now waiting for vpnclient to finish

diff --git a/vpnmanager b/vpnmanager
--- a/vpnmanager
+++ b/vpnmanager
@@ -120,15 +120,6 @@ set_route_to_vpn () {
     ip route replace "$ip/32" via "$default_gw" dev "$default_dev"
 }
 
-res=$($VPNCLIENT start)
-
-if [ "$?" -ne "0" ]; then
-    echo "Unable to start vpnclient: $res"
-    exit 3
-else
-    sleep 2
-fi
-
 if [ "$#" = 0 ]; then
     echo "Not enough arguments"
     echo ""
@@ -324,8 +315,20 @@ while [ "$1" != "" ]; do
     shift
 done
 
+$VPNCLIENT execsvc &
+
+service_pid="$!"
+
+if [ "$?" -ne "0" ]; then
+    echo "Unable to start vpnclient"
+    exit 3
+else
+    sleep 2
+fi
+
 # create adapter if not exist
-if [ ! -f "/dev/vpn_$VPN_ADAPTER" ]; then
+res=$($VPNCMD /CLIENT localhost /CMD NicList | grep "Virtual Network Adapter Name.* $VPN_ADAPTER")
+if [ ! "$?" -ne "0" ]; then
     res=$($VPNCMD localhost /CLIENT /CMD NicCreate $VPN_ADAPTER)
 
     if [ "$?" -ne "0" ]; then
@@ -456,4 +459,5 @@ fi
 vpn_gw=$(grep 'routers' /var/lib/dhcp/dhclient.leases | awk '{ print substr($3, 1, length($3)-1) }')
 ip route replace default via "$vpn_gw" dev "vpn_$VPN_ADAPTER" metric 1
 
-/bin/bash
+
+wait $service_pid
